# Generated by Django 4.1.4 on 2022-12-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_states_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='contributor',
        ),
    ]
