# Generated by Django 3.0.1 on 2022-04-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatesAndCapitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=250)),
                ('capital', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
            ],
        ),
    ]
